### PR TITLE
fix servo sensing calculation

### LINKED ISSUE #42: Position unit is revolution not radians
I think that the driver returns position as a revolution, not radians. I checked the code and I didn't find any conversion from revolution to radians.

### LINKED ISSUE #53: rpm calculation is not correct
## Abstract

Motor does not rotate at correct speed even though `gear_ratio` and `num_motor_pole_pairs` are set correctly.

### LINKED ISSUE #56: vesc shows undesirable position on start up when using combined hardware interface
## Abstract
This is what happens when we use vesc_hw_interface with combined hardware interface
Screenshot from 2022-12-15 16-04-38

Both wheel joints should be 0.0 on initialization, but the image shows different values.

The problem is probably here
https://github.com/sbgisen/vesc/blob/f8d522070c3a44035a2e4a76c029da9296adf1de/vesc_driver/src/vesc_packet.cpp#L282-L287

Static variables are shared between threads which is not ideal for this particular case. We should have independent variables for threads.

### LINKED ISSUE #59: [vesc_hw_interface] enabling revolution-type joint
## Abstract
* vesc_hw_interface's vesc_servo_controller has a mode for revolution-type joint, but it's untested and needs work.

### PR DESCRIPTION
**Pull request by jsupratman13**
## Change Summary
* Probably resolve #42 
* resolve #53 
* resolve #56 
* resolve #59 
* Fix the unit conversion from sensor data and adjust the units for each joint type.
* Replace the static variable with members to avoid the thread-sharing bug

## Impacts

* Probably need to set the proper parameters and tune PID gain again.

## Additional Information

* Note that this only fixes the sensor calculation and, to an extent, the calibration process.
* This is tested with PRISMATIC joints since we use this often with vesc. 
* REVOLUTION joint is untested. There is still a lot of work needed to be done with this joint type which, if I have time, will be worked on in later PRs.

### CODE REVIEW

File: vesc_hw_interface/src/vesc_hw_interface.cpp [hunk 1]
```diff
@@ -299,12 +317,11 @@ void VescHwInterface::packetCallback(const std::shared_ptr<VescPacket const>& pa
...
     const double current = values->getMotorCurrent();
     const double velocity_rpm = values->getVelocityERPM() / static_cast<double>(num_rotor_poles_) / 2;
-    const double position_pulse = values->getPosition();
+    const double steps = values->getPosition();
 
-    // 3.0 represents the number of hall sensors
-    position_ = position_pulse / (num_hall_sensors_ * num_rotor_poles_) * gear_ratio_;  // unit: rad or m
-    velocity_ = velocity_rpm / 60.0 * 2.0 * M_PI * gear_ratio_;                         // unit: rad/s or m/s
-    effort_ = current * torque_const_ / gear_ratio_;                                    // unit: Nm or N
+    position_ = steps / (num_hall_sensors_ * num_rotor_poles_) * gear_ratio_;  // unit: rad or m
```
Comment (Tacha-S) [inline vesc_hw_interface/src/vesc_hw_interface.cpp:322]: Don't you take overflow into account?

File: vesc_hw_interface/src/vesc_servo_controller.cpp [hunk 2]
```diff
@@ -1,5 +1,5 @@
 /*********************************************************************
- * Copyright (c) 2019, SoftBank Corp.
+ * Copyright (c) 2022, SoftBank Corp.
```
Comment (Tacha-S) [inline vesc_hw_interface/src/vesc_servo_controller.cpp]: Revert to `2019`.
This is published year.

File: vesc_hw_interface/src/vesc_servo_controller.cpp [hunk 3]
```diff
@@ -209,14 +222,14 @@ bool VescServoController::calibrate(const double position_current)
...
   }
 
-  step++;
+  calibration_steps_++;
 
-  if (step % 20 == 0)
+  if (calibration_steps_ % 20 == 0)
   {
-    if (position_current == position_previous)
+    if (position_current == calibration_previous_position_)
```
Comment (Tacha-S) [inline vesc_hw_interface/src/vesc_servo_controller.cpp]: Do not compare double with `==`.
If these variables are same value, You can use [machine epsilon](https://cpprefjp.github.io/reference/limits/numeric_limits/epsilon.html).

File: vesc_hw_interface/src/vesc_servo_controller.cpp [hunk 4]
```diff
@@ -209,14 +222,14 @@ bool VescServoController::calibrate(const double position_current)
...
     {
       // finishes calibrating
-      step = 0;
+      calibration_steps_ = 0;
       zero_position_ = position_current - calibration_position_;
       position_sens_ = calibration_position_;
       position_sens_previous_ = calibration_position_;
```
Comment (Tacha-S) [inline vesc_hw_interface/src/vesc_servo_controller.cpp]: Why is it different from this?
https://github.com/sbgisen/vesc/blob/dc6b62055cef148e0524d16b4da184705841972e/vesc_hw_interface/src/vesc_servo_controller.cpp#L90

**Review by Tacha-S — CHANGES_REQUESTED** [review]

File: vesc_hw_interface/src/vesc_hw_interface.cpp (hunk 1 above)
Comment (jsupratman13) [reply vesc_hw_interface/src/vesc_hw_interface.cpp:322]: I was planning to unite `updateSensor` function (refactor vesc_hw_interface.cpp, vesc_servo_controller.cpp, vesc_wheel_controller.cpp to reduce code maintenance etc.) on the next PR and handle any lingering unit conversion and overflow.

But I could do it here if you prefer it.

File: vesc_hw_interface/src/vesc_servo_controller.cpp (hunk 2 above)
Comment (jsupratman13) [reply vesc_hw_interface/src/vesc_servo_controller.cpp]: ok

File: vesc_hw_interface/src/vesc_servo_controller.cpp (hunk 3 above)
Comment (jsupratman13) [reply vesc_hw_interface/src/vesc_servo_controller.cpp]: Thanks for the info.

File: vesc_hw_interface/src/vesc_hw_interface.cpp (hunk 1 above)
Comment (Tacha-S) [reply vesc_hw_interface/src/vesc_hw_interface.cpp:322]: > I was planning to unite updateSensor function (refactor vesc_hw_interface.cpp, vesc_servo_controller.cpp, vesc_wheel_controller.cpp to reduce code maintenance etc.) on the next PR and handle any lingering unit conversion and overflow.

Ok. :+1:

File: vesc_hw_interface/src/vesc_servo_controller.cpp (hunk 4 above)
Comment (jsupratman13) [reply vesc_hw_interface/src/vesc_servo_controller.cpp]: That's a very good question. I probably missed that line on #48.

Will remove.

**Review by Tacha-S — APPROVED** [review]

**Review by nyxrobotics — APPROVED** [review]
I checked the source code because I don't have a test environment.
